---
include:
  - board: nice_nano_v2
    shield: cygnus_central_dongle dongle_display
    artifact-name: cygnus_central_dongle
  - board: nice_nano_v2
    shield: cygnus_central_left
    artifact-name: cygnus_central_left
  - board: nice_nano_v2
    shield: cygnus_peripheral_left
    artifact-name: cygnus_peripheral_left
  - board: nice_nano_v2
    shield: cygnus_peripheral_right
    artifact-name: cygnus_peripheral_right
  - board: nice_nano_v2
    shield: settings_reset
    
